
public interface MarsConstants {
	float SCALE_REDUCTION = 2;
	int ROBOT_NUMBER=100;
	int ROBOT_VIEW_DISTANCE= 200;
	int OBSERVATION_DISTANCE= 5;
	int ROBOT_RADIAN = 4;
	int LAUNCH_WAIT_TIME = 100;
	int MOVE_WAIT_TIME = 10;
	int SCREEN_X_SIZE = 1800;
	int SCREEN_Y_SIZE = 1000;
	int MAP_X_POSITION = SCREEN_X_SIZE/2;
	int MAP_Y_POSITION = SCREEN_Y_SIZE/2;
	int TEST_BOT = 1;
	int FINISHED_DISTANCE = 1;
	float ORIENT_VECTOR_ENLAGEMENT = 20;
	float MOVE_DISTANCE = 1;
	float SPEED_REDUCTION = 0.002f;
	float MINIMAL_ORIENTATION_DIFFERENCE = 0.1f;
	float COMBINATION_DISTANCE = 2;
	
	
	boolean VIEW_CIRCLES_ON = true;
	boolean ANIMATED_LAUNCH = true;
	boolean TEST = false;
	boolean STOP_WHEN_FINISHED = true;
}
